#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : librealsense
Version  : 0.9.1
Release  : 1
URL      : https://github.com/IntelRealSense/librealsense/archive/v0.9.1.tar.gz
Source0  : https://github.com/IntelRealSense/librealsense/archive/v0.9.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 LGPL-2.1
Requires: librealsense-lib
BuildRequires : libusb-dev
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(glfw3)
BuildRequires : pkgconfig(glu)
Patch1: 0001-makefile-fix-install-target.patch
Patch2: 0002-makefile-add-soname-to-library.patch
Patch3: 0003-makefile-support-Clear-Linux-compiler-flags.patch

%description
# IntelÂ® RealSenseâ¢ Cross Platform API
[ ![Release] [release-image] ] [releases]
[ ![License] [license-image] ] [license]

%package dev
Summary: dev components for the librealsense package.
Group: Development
Requires: librealsense-lib
Provides: librealsense-devel

%description dev
dev components for the librealsense package.


%package lib
Summary: lib components for the librealsense package.
Group: Libraries

%description lib
lib components for the librealsense package.


%prep
%setup -q -n librealsense-0.9.1
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install prefix=/usr LIB_SUFFIX=64

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/librealsense/rs.h
/usr/include/librealsense/rs.hpp
/usr/include/librealsense/rsutil.h
/usr/lib64/*.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
